# Generated by Django 5.2.4 on 2025-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0002_alter_estadoemocional_usuario_alter_registro_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='url_preview',
            field=models.URLField(blank=True, null=True),
        ),
    ]
