# Generated by Django 5.2.4 on 2025-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0003_cancion_url_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='sentimiento_asociado',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
