# Generated by Django 5.2.4 on 2025-08-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0004_remove_cancion_enlace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
