# Generated by Django 5.2.4 on 2025-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0005_alter_cancion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='url_preview',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
